### ISSUE TITLE
[Bug]: Emulator crashes immediately upon loading save state.

### ISSUE THREAD

**Issue by idislikebaguettes** [visualboyadvance-m/visualboyadvance-m#1153]
### Expected behavior?

Successful loading of save state, maybe even produce the list as it is supposed to when I select Load State...

### Actual behavior?

Emulator crashes immediately upon loading. **I have not used since the major update that apparently changed its icon and a bunch of other things, so this may have an impact. However, I worked very hard on this save. I was close to completing the Pokedex as far as I can remember.** Won't even load my normal .sav file on bootup while something like PkHEX will.

### Steps to reproduce the problem

1. Open Emulator.
2. Load ROM file (.gbc file)
3. Hit Load State... and then From File...
4. Select the desired file.
5. Emulator crashes.
...

### Error messages?

(I do not have appropriate tools to produce this, I apologize.)

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokemon Gold
GB, GBC or GBA: GBC
SAVE TYPE: .sgm, .sav

### What settings are you using?

N/A, first use of visual boy advance since major update

### Specifications and Build details

VBA-M: 64-bit
OS: Windows 11
Processor	12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	B6CA3AAB-9617-4CEF-98B8-D2D1E19D0C7D
Product ID	00342-20810-81605-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
2.1.5 had a bios regression that might be relevant, which is fixed in 2.1.6

**Comment by idislikebaguettes** [comment]
> 2.1.5 had a bios regression that might be relevant, which is fixed in 2.1.6

The only one I can download on Window 11 is 2.1.5 from the website, is there a link somewhere to 2.1.6?

**Comment by Squall-Leonhart** [comment]
We don't have any connection to "That" website, ours has 2.1.6 has the latest post, and can be obtained from our [release section ](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.6)

**Comment by idislikebaguettes** [comment]
> We don't have any connection to "That" website, ours has 2.1.6 has the latest post, and can be obtained from our [release section ](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.6)

I tried that and am still getting the same issue. Also, the states aren't showing up in the Load State list... even though they have the same name as the ROM (excluding the (1), (2), etc.), are in the same folder, and have the .sgm filetype.

**Comment by idislikebaguettes** [comment]
Okay, it seems to work now that I'm using an older version of VBA, so I will use that in the meantime while I try to figure the rest out

**Comment by Squall-Leonhart** [comment]
This sounds like some bitdefender bs blocking the states, but we don't support states from 1.8.x or older being used in 2.0 anyway, not that many of them won't work but theres too many differences between then and now.

**Comment by ZachBacon** [comment]
> > 2.1.5 had a bios regression that might be relevant, which is fixed in 2.1.6
> 
> The only one I can download on Windows 11 is 2.1.5 from the website, is there a link somewhere to 2.1.6?

Sounds like you didn't get your copy from our official website. All our releases are found at https://vba-m.com and nowhere else.

**Comment by Squall-Leonhart** [comment]
Are you sure you downloaded the 64bit binary? i have a reproduction of this now, but only with the 32bit release.

**Comment by QB64Cobalt** [comment]
I have a similar experience with Pokemon Gold (and Silver&Crystal) when loading save states the memory seems to get corrupted. If I'm in the middle of a battle and load a save state weird messages may start displaying, or the graphics become glitched, or  all the pokemon moves disappear, or on rare occasions the game resets(though the palette is still all wack until I reload the rom). This occurs in ver. 2.1.8. 
Also, it is probably just my imagination but, different save slots seem to have a higher tendency to cause this too, rarely on slot 1, almost never on slot 2, slot 3 is almost 50/50, and slot 4 is nearly all the time(but not every time). Haven't tried higher save slots. Probably just my imagination though.
Not sure if it would have something to do with the Pokemon games using the clock for stuff, so when you load a save state the clock suddenly might change and throw things off? Not sure just what all is stored in the save states. Wondering this cause I've had issues with the National Park Contest, as that is a timed event.

**Comment by Steelskin** [comment]
I'm trying to understand the exact issue you are hitting. You can help me by answering these questions:

1. When you load a specific save state, does it crash consistently?
2. If not, can you make it crash consistently by repeating certain steps? e.g. "Start a battle -> Load during battle -> Crash"?

If you can reproduce the issue consistently, please upload the faulty save state file.

**Comment by QB64Cobalt** [comment]
just so happens that I have a save state acting up right now, if you load the state and try to access "PACK" it will lock up\crash, if you choose "ATTACK" then cancel back and choose "PACK" you get one of the weird messages then it locks up\crashes.(screen cap included), Choosing "PkMn" locks up\Crashes, the "RUN" option gives the message "no running from trainer battle:" but any option after that gives the same message as the included screen capture then locks up\crashes. You can run 1 "ATTACK" and it works as it should but then all options display the message and lock up\crash. I have tried it a few times now and this save state is consistent with the same results on my end. 

![Image](https://github.com/user-attachments/assets/efea5819-8e95-46d3-9fff-bbb62338cdc0)

[Pokemon - Gold Version (USA, Europe)-02.zip](https://github.com/user-attachments/files/19409927/Pokemon.-.Gold.Version.USA.Europe.-02.zip)

It wouldn't let me upload the SGM directly so I had to ZIP it. 
One of the more rare times that it affected slot 2(again may just be my imagination there though)

**Comment by Squall-Leonhart** [comment]
2.1.8 is not current, update and your issues will cease.

**Comment by QB64Cobalt** [comment]
Which of course that means that if I test out what you suggest to see that it works I will destroy the actual saved game.... ah well 8 hours flushed down the toilet.

That probably wouldn't have any effect on the gameshark codes that have to be re-entered every so often cause they suddenly stop working would it?

I didn't see that the new versions are hosted on git now, I was trying to pull up the vba-m site, which isn't working. (honestly can't remember where I picked up my copy of 2.1.8 it was so long ago.)

**Comment by Squall-Leonhart** [comment]
> Which of course that means that if I test out what you suggest to see that it works I will destroy the actual saved game.... ah well 8 hours flushed down the toilet.

As long as you don't trigger the battery backup in any way it shouldn't overwrite the save, you need to actually save again on the restored save.

It does work though, i tested your sgm file and the freeze on closing out of PACK and the debug message are both mitigated by restoring all the memory.

**Comment by QB64Cobalt** [comment]
> As long as you don't trigger the battery backup in any way it shouldn't overwrite the save, you need to actually save again on the restored save.
> 
> It does work though, i tested your sgm file and the freeze on closing out of PACK and the debug message are both mitigated by restoring all the memory.

for what ever reason it did.  I turned that option off then loaded that state to see if it worked( yes it in fact worked great) then I clicked on the "Emulation" menu and 'Reset' the game to load back where I was. only to find the the game loaded back to where the save state had been; same levels as the save state, same pokemon in group, pokedex back to where it was at that time. the location was off and the hours played were off too.
I didn't even finish that battle, I just checked to see if it no longer locked up\crashed on accessing the menu options.
I saved the game right before testing the save state so I could reload back to where I was.

**Comment by Squall-Leonhart** [comment]
Closing this. because it stems from not restoring all game memory.
