### ISSUE TITLE
Pressing input buttons freezes the emulator

### ISSUE THREAD

**Issue by Ammako** [visualboyadvance-m/visualboyadvance-m#54]
When I press the keys I've selected in Joypad Configuration, the emulator hangs, for as long as the key is being held.
This makes doing anything in a game virtually impossible.
This is using the Beta-3 compiled release from 4 days ago (c2a23a9).

**Comment by rkitover** [comment]
I'm sorry we did not have an issue template, I just added one, can you please give some information about your configuration:

Operating System
Interface (wX, GTK, etc.)
Build (is this the pre-built or your own build)

Thanks!

**Comment by Ammako** [comment]
Running Windows 8.1 Pro, honestly not sure about Interface, but like I said I'm using the pre-built Beta-3 release from 4 days ago. Github says it's from commit f7f67ff, the .exe says it's from c2a23a9 though.

### Expected behavior
I expect that key presses trigger the actions or button presses they are mapped to.

### Actual behavior
The emulator hangs whenever any of the keys I've configured are held down (also causes the audio to be stuck in a loop exactly like what happens in #45, I don't think the two issues are related though.) 

### Steps to reproduce the behavior
Run the emulator, load a game, press any keys that have been configured (it isn't limited to standard controls, special hotkeys also cause the same issue.)

### Build details

Operating System (Windows, Mac, Linux, etc.): Windows 8.1 Pro

Interface (wX, GTK, SDL, MFC, default is wX): Not really sure how to check, but ↓

Version of code (pre-built binary version, or commit ref, or just "master"): Using [pre-built binary version.](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/Beta-3)

**Comment by rkitover** [comment]
I have issues myself on windows with the keyboard while other people don't, there is something weird going on with this, perhaps we will use SDL for keyboard input at some point.

Right now trying to figure out if this is an issue specific to this build.

One thing you can try is installing msys2, starting the MINGW 32 shell, and running `./installdeps` and following the instructions to try your own build.

**Comment by Ammako** [comment]
Well, I tried. [Can't compile.](http://pastebin.com/K5trB93L)
This is straight from the repo, I'm fairly certain I'm not missing any files from it, no clue what I may be doing wrong (if it's on my end.)

**Comment by rkitover** [comment]
Oh sorry, that was a PR we just merged earlier today...

**Comment by rkitover** [comment]
@Ammako should be fixed, please try again! The `#include` statement in that PR was wrong.

**Comment by Ammako** [comment]
Well, it does compile, doesn't run unless I place it in mingw32\bin since it complains about every single dependency being missing and I don't really want to register all of these since I don't think it should be necessary.

Anyway, it compiles, and it runs, but not very well. The input bug is still there, but [this also happens](https://puu.sh/sUFrd/9cf2306844.png) on most games.
LoZ: A Link to the Past still looks normal though, not sure what makes it any different from the others.

**Comment by rkitover** [comment]
Are you using a VM or something like that?

Also you can run it from the shell by just typing ./visualboyadvance-m

**Comment by Ammako** [comment]
Nope, this is a regular Windows install. I have Beta 2 from Sourceforge which works fine in every way, the pre-built Beta 3 looks normal aside from that input problem, but this compiled version has a messed up display on my end for some reason.

(I didn't realize that running it directly from mingw32 would automatically get the dlls, that's good to know.)

**Comment by rkitover** [comment]
Alot of really weird shit has been happening with this project, first the keyboard broke in two interfaces between minor builds where there was no code related to the keyboard at all, now this crap.

**Comment by Ammako** [comment]
Am I the only one who has been having this problem, or has anybody else experienced it?
I can compile a bunch of versions and figure out where it stops working, could be a long hunt though since I wouldn't be able to tell exactly when that started.
For the graphical problem there's still a possibility it's an issue on my end making it compile or run wrong, unless other people are getting the same results. I guess I'll try compiling the same version as was used for the pre-built and see.

**Comment by DoctorWho11** [comment]
At the moment we know of the issue and are working to fix it. Be patient. As for xaudio2 you need to download the git master using git clone https://GitHub.com/visualboyadvance-m/visualboyadvance-m.git and then the installdeps script will clone the proper git submodule to allow xaudio2 support.

**Comment by rkitover** [comment]
@Ammako I heard of more issues with LTO so I disabled it on Win32 for the time being, can you try to build again (with master) and see if it fixes the artificats and such?

**Comment by Ammako** [comment]
The same problem with graphics is still present, along with the input problem.

**Comment by rkitover** [comment]
@Ammako Can you try both the Simple and the OpenGL renderer and see which one has the graphics issue?

**Comment by Ammako** [comment]
I did, and I didn't see a difference.

**Comment by rkitover** [comment]
@Ammako Ok thanks! So it must be an emulation bug. Just to make sure the hardware is fine, does your windows run stable without crashes and blue screens? Have you run memtest86 at any point recently?

**Comment by Ammako** [comment]
I don't remember any blue screens since I got it about two years ago. Closest thing to a crash was from the battle.net app, which gets very unstable if I leave it running while updating gpu drivers, otherwise nothing.

As for memtest, I haven't.

**Comment by rkitover** [comment]
@Ammako 

Just an update, I can reproduce the emulator freezing on button presses issue now in my windows VM, so I should be able to figure out a fix soon, just as soon as I figure out how to make it show a debug console in windows.

This seems to be some kind of strange random issues in how wxWidgets handles the keyboard.

**Comment by rkitover** [comment]
@Ammako Hey if you are still interested, I think I fixed the game-freezing-on-keypress issue in 6ecab805, please give master a try.

This was a difficult one, I had to fix debug logging before I could actually debug anything, and then figure out what was happening.

**Comment by Ammako** [comment]
That problem seems to be gone, graphics are still completely messed up though :s

**Comment by rkitover** [comment]
@Ammako Thanks for testing!

So the messed up graphics are visible in Pokemon Ruby, my copy of the ROM works correctly, it seems to be a modded one.

Can you please give me your email address so I can send you my copy (me posting a link would be illegal or something like that.)

I want to rule out the issue being the ROM itself.

Just email me at rkitover@gmail.com .

**Comment by rkitover** [comment]
@Ammako 

Or, if you don't want to do that, find a ROM collection on a good tracker with a lot of seeds, those should be of relatively high quality.

Here is the shasum of my ROM, you can run this command in the msys2 shell:

```bash
shasum -a 256 Pokemon\ -\ Ruby.gba
f6eb19ce9a42b4bcf65062eb3129b494e1f3b2fd0685ec0790e2fc4e62bb6e72 *Pokemon - Ruby.gba
```

**Comment by rkitover** [comment]
@Ammako 

Just tried another version of this ROM, also works correctly:

```bash
shasum -a 256 ./2006\ -\ Pokemon\ -\ Ruby\ Version\ \(E\)\ \(v1.2\).gba
0fdd36e92b75bed65d09df4635ab0b707b288c2bf1dc4c6e7a4a4f0eebe9d64c *./2006 - Pokemon - Ruby Version (E) (v1.2).gba
```

**Comment by Ammako** [comment]
fwiw, that first rom you were trying -is- a modded rom (scene release group intro.) Not that it really matters anyway, because it has the same problem.

Mine isn't a modded rom, it's a direct dump from my retail cartridge. Every Pokémon game has the exact same problem (all direct dumps from my retail cartridges.) I also tried a 1.0 dump from the internet (CRC32: F0815EE7, which is what ADVANsCEne has listed), which has the same problem (I doubt that different revisions of the same game would have different problems in emulators, anyway.)

Must be something about those specific games, since they all run on the exact same engine; makes sense that a bug like this may affect all of them. I've tried a couple of other games, as expected none of them have that problem, including Legend of Zelda: A Link to the Past which was also a direct dump from my retail cartridge, so I don't think anything's getting corrupted in any way when I dump the roms.

If you aren't getting that problem, could you link your copy of the compiled latest commit? (with all its .dlls, or perhaps merged into the .exe, in case the ones I have are problematic somehow.) If I don't have those problems with the one you compiled then this would mean my compiling environment is causing the issues, and if I do, then it would mean something else on my computer is causing those problems.

**Comment by rkitover** [comment]
@Ammako also update your msys2, there have been some updates very recently, run these commands in the mingw shell:

```bash
pacman --needed -Syu base
pacman -Syu
```

If it tells you to close your terminal and run the command again, close the window and run:

```bash
pacman -Syu
```

again.

Hopefully I can do my little project soon to make mxe available on cygwin and we can forget about msys2 entirely.

I will make you a test build of master with mxe (static) there was just one issue with that build I need to fix.

**Comment by rkitover** [comment]
@Ammako @DoctorWho11 will do a new tag/build in a few hours.

**Comment by rkitover** [comment]
@Ammako Please try this build:

https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/Keyboardfixes

**Comment by Ammako** [comment]
Yeah, that one works fine. Guess something's going wrong on my end with the compilation.
(Noticed that those builds take a bit longer to load for basically everything, like a little bit longer to load the emulator, a few seconds to correctly load the files list, a few seconds for the game to load, and a few seconds for the emulator to close when you X out, not sure if that's just me. But the problems with graphics being messed up is gone.)

**Comment by rkitover** [comment]
Well, mingw-w64 is very buggy, and it's possible you are triggering some kind of bug in the gcc port somehow, it's also possible that it's a hardware problem (like bad RAM.)

Compilation is a **very** CPU and memory intensive process and failures can often indicate hardware problems.

To rule out hardware issues, I would suggest a couple of things:

run memtest86:

http://memtest.org/#downiso

you write that to a USB stick, boot it and let it run for about half an hour. If there's no red on the screen, the memory is probably good.

run prime95 torture test:

http://www.mersenne.org/download/

install that and select "torture test" when it runs, let it run for a like...10-20 minutes or so while you are doing other stuff, like browsing pages. If while doing this you notice weird things like apps closing themselves or throwing errors, or the computer freezes, blue-screens or reboots, that would indicate that the system isn't stable.

While doing this you can also use CPU-Z (http://www.cpuid.com/softwares/cpu-z.html) to monitor the CPU frequency and Core Temp (http://www.alcpu.com/CoreTemp/) to monitor CPU temperatures.

If you see that the frequency is throttling back as temperatures rise, it means you need a better CPU cooler (and/or to clean out some dust etc.) but does not in itself indicate a stability issue.

If you do these two things, and there are no errors/crashes, then that would rule out most hardware issues. And if you do, let me know what you find.

What is the CPU in that system by the way?

**Comment by Ammako** [comment]
I have an Intel Core i5-4690 @ 3.50GHz

Nothing out of the ordinary has really happened with prime95, all that happened is that my CPU temperature eventually passed 80c after some time at which point I stopped it. Everything I was doing was just fine.

memtest may have to wait until later, since being unable to use the computer for anything else the entire time isn't the most convenient, but I can make time for it and come back with that later.

(If it might provide some insight as to what is happening, I can copy/paste the output when I do the compilation, maybe there could be some error messages in it or something.)

**Comment by rkitover** [comment]
@Ammako hey, are you interested in debugging your build issues any further or should I close this?

What I meant to say in my last post, is, do a scan with [malwarebytes](https://www.malwarebytes.com) and [adwcleaner](https://www.bleepingcomputer.com/download/adwcleaner/) and try to do a clean build (`rm -rf build/*` first) with any anti-virus and personal firewall software disabled. Then see if your compiled object has the same issues or not.

Since it seems that the system is stable (even without checking memtest86) it seems like a problem with malware or an anti-virus of some sort.

**Comment by Ammako** [comment]
I had an idea and tried it; turns out that if I build using mingw64 rather than mingw32, everything works fine (or at least, the graphics aren't broken.)

**Comment by rkitover** [comment]
@Ammako 

The difference is, when you do a 32 bit build it builds the ASM source filters with nasm, and since we don't have any 64 bit ASM, 64 bit builds only use pure C/C++.

Are you using any filters? (such as XBRZ6/HQ4X/etc.)

**Comment by rkitover** [comment]
@Ammako 

To replicate the options in the 64 bit build with the 32 bit build, try the following cmake invocation:

```bash
cmake .. -G 'MSYS Makefiles' -DENABLE_ASM_CORE=OFF -DENABLE_ASM_SCALERS=OFF -DENABLE_MMX=OFF
```

**Comment by Ammako** [comment]
Yeah, with that it builds and all works properly through mingw32.

Don't think I use any filters, as far as I'm aware those have to be enabled manually, and I never use those.

**Comment by rkitover** [comment]
@Ammako 

So I think we can be reasonably certain now that it is the ASM core that is causing issues, and for some reason on your machine and not on others.

To check if you are using a filter, go to Options -> Video -> Configure, and on the first page for "Display filter" it should say "None".

**Comment by Ammako** [comment]
No filters, no.

**Comment by rkitover** [comment]
So, we know that the problem is with the asm emulator core and only your machine (which has some rare characteristic that some others may also have, I still cannot imagine **WHAT** it is though.)

It seems to affect the GBA framebuffer but not the game mechanics, presumably, or it would just crash or something.

So the next step would be to check if any framebuffer and/or memory related code in the core is doing anything such as using uninitialized variables. And/or if the framebuffer memory is being initialized properly.

My guess would be that since the bug only affect some games and not others, it may be a difference in how e.g. the pokemon games use the framebuffer as opposed to the other games, the games that work may be initializing the memory while the pokemon games assume that it is initialized by the system.

Fixing all the compiler warnings in the core may help with this, or it may not, and is going to be a huge amount of work, there are **a lot** of warnings.

I'm sorry for asking you to do a lot of what turned out to be completely irrelevant things.

Not sure when and if I will get to doing this (especially since it's a relatively minor issue with a simple workaround) just wanted to post a summary.

**Comment by Ammako** [comment]
It's ok heh, if I didn't want to do those things I wouldn't have ;)

Might be worth marking this as resolved since the original issue of the thread was indeed fixed, although I guess it's really up to you, if you want to keep this one up just to keep track of this weird compilation problem.

**Comment by rkitover** [comment]
Yeah, I was on some very bad drugs when I wrote my last post or something and forgot that this is actually a **compilation** issue and not a runtime issue, but the idea is the same, something in the way inline assembly gets compiled on your machine leaves a register or memory area uninitialized, would be the best guess for the issue.

I changed the title of the issue so that if anyone else runs into this they can find it.

Perhaps if we look at the ARM core in the future and replace it with the ARM core from some other project, or improve the code or whatever, the problem will go away. Things like Dolphin actually have a JIT for translating ARM to native code, that would certainly be a neat thing to steal.

**Comment by rkitover** [comment]
An update on this:

in #98 we've determined that the inline asm CPU core causes executables on Linux to crash on startup, so it definitely has problems, and I changed the default to disable it when building.

At some point we will investigate how to replace it with an ARM core from another project, such as from MAME.
