### ISSUE TITLE
Various Bugs on Win 10

### ISSUE THREAD

**Issue by javidg96** [visualboyadvance-m/visualboyadvance-m#90]
Hello. I'd like to report some bugs I encountered on the last released build (2.0.0 Beta)

**Bug descriptions:**
1st. Whenever I change the audio volume, the application crashes.

2nd. Whenever I click outside the application while a game is running, the audio freezes and loops instead of getting muted -this only occurs when 'Pause when inactive' is checked-.

3rd. Whenever I try to load a save state -for instance _F1_- while on full screen mode, the application crashes.

4th. I can't connect two instances of the program using the 'Link' feature.

**Steps to reproduce:**
1st. Open the application, go to _Options>Audio>Configure..._; Drag the volume selector into another position, hit _OK_.

2nd. Open the application, make sure 'Pause when inactive' is checked. Run a game. Click anywhere outside the application.

3rd. Open the application, save a state, go into full screen mode (F11), hit the macro button for the state you saved (F1, F2...).
**Note**: It seems this bug is more likely to appear if you have just been using the 'speed up' function.

4th. Open two instances of the application and on each one load a game -I'm using Pokémon Blue and Pokémon Yellow-; On both instances, go to _Options>Link>Type_ and select 'Cable'. Then, on each instance again, go to _Options>Link>Start Network Link..._. Next, choose one to be the Server, select 2 players and hit 'Start'. On the other one, select 'Client' and fill the 'Server' field with your local IP; Hit connect. The game will now inform you that the two players are connected. However, trying to engage in multiplayer activity will be futile. 
**Note**: I think this may have something to do with the 'Pause when inactive' option. I unchecked it on both instances. But I can't control both of them at the same time: I need to click on each one, then go to the "cable club" individually, unlike with VBA Link -which isn't working for me either-.

**ROM details:**
Player 1: Pokémon Blue (Spanish) [Personal dump] GB
Player 2: Pokémon Yellow (Spanish) [Personal dump] GB

**Video driver:** simple.

**Sound driver:** directsound.

**Build details:**
Operating System: Windows 10 Home (OEM).
Version of code: Last Released Build (2.0.0 Beta)

**Comment by rkitover** [comment]
@javidg96 The sound looping bug should be fixed in the latest build, have you tried the latest build from the releases link?

The other bugs have issues open.

Link should work, please try latest build and get back to me. Try `127.0.0.1` for the IP.

**Comment by javidg96** [comment]
@rkitover Yes. It's the last release from SourceForge (2.0.0_beta2).

The instances did connect using that IP, but I can't get the games to connect. I left everything unchecked except for the link type (cable). Could it be possible that my AV software is preventing the connection?

Thank you very much for your quick response. I love this emulator.

**Comment by rkitover** [comment]
@javidg96 we are slowly getting off of sourceforge, the latest builds are on github here:

https://github.com/visualboyadvance-m/visualboyadvance-m/releases

**Comment by rkitover** [comment]
@javidg96 the sound looping when paused bug should be fixed in the last build.

As for link, it should work, what actually happens when you try it? If you choose link type cable, start a server on one instance and connect to the server on another instance, does it say all players connected?

**Comment by javidg96** [comment]
@rkitover I just tried it again; It does still loop when I check 'Pause when inactive'.

The on-screen display says that "all players connected", but when I try to link both games, connection does not happen. Eg. In the case of 1st gen Pokémon games, they'll say "This area is reserved for 2 friends who are linked by link cable".

**Comment by rkitover** [comment]
@javidg96 are you sure you are actually using the last build? It's the one that says 'waylandplus', specifically [this file](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/download/waylandplus/vba-m-x86_64.zip).

As for link, I will try with pokemon blue and see if there are any issues.

**Comment by javidg96** [comment]
@rkitover Oh, right. I went for the other one because this one was labeled "Pre-Release"... I'm sorry.

The sound loop bug is fixed now, but I still can't link the games. Same issue. One instance outputs "all players connected", the other "all players joined". Actual connection between the ROMs is not happening, however.

Thanks for looking into it.

**Comment by Squall-Leonhart** [comment]
closing this because  all issues bar linking have been addressed, and there are enough issues for linking as is.
